init:
    #BGS, CGS, AND ZERO GS
    image bg bridge1 = "Bg/bridge1.png"
    image bg bridge1e = "BG/bridge1e.png"
    image bg bridge1n = "BG/bridge1n.png"
    image bg bridge2 = "BG/bridge2.png"
    image bg bridge2e = "BG/bridge2e.png"
    image bg bridge2n = "BG/bridge2n.png"
    image bg bridge3 = "BG/bridge3.png"
    image bg bridge3e = "BG/bridge3e.png"
    image bg bridge3n = "BG/bridge3n.png"
    image bg bridge4 = "BG/bridge4.png"
    #WEETABIX NOTE: Killed bg bridge5 temporarily for great justice
    #image bg bridge5 = "BG/bridge5.png"
    image bg bridge5n = "BG/bridge5n.png"
    image bg bridge6 = "BG/bridge6.png"
    image bg water1 = "BG/water1.png"
    image bg water1n = "BG/water1n.png"
    image bg lot1 = "BG/lot1.png"
    image bg lot2 = "BG/lot2.png"
    image bg lot3 = "BG/lot3.png"
    image bg lot4 = "BG/lot4.png"
    image bg food1 = "BG/food1.png"
    image bg store1 = "BG/store1.png"
    image bg house1 = "BG/house1.png"
    image bg house1e = "BG/house1e.png"
    image bg house1n = "BG/house1n.png"
    image bg house2 = "BG/house2.png"
    image bg house2n = "BG/house2n.png"
    image bg house_in1 = "BG/house_in1.png"
    image bg house_in2 = "BG/house_in2.png"
    image bg park1 = "BG/park1.png"
    image bg park2 = "BG/park2.png"
    image bg park3 = "BG/park3.png"
    image bg park4 = "BG/park4.png"
    image bg street1 = "BG/street1.png"
    image bg street1n = "BG/street1n.png"
    image bg end1 = "BG/end1.png"
    image bg end2 = "BG/end2.png"
    image bg end3 = "BG/end3.png"
    image bg end4 = "BG/end3.png"
    # CHARACTER SPRITES. THANK YOU AND OBEY.
    image eve 1 = "Eve/1/eve_1.png"
    image eve 2 = "Eve/1/eve_2.png"
    image eve 3 = "Eve/1/eve_3.png"
    image eve 4 = "Eve/1/eve_4.png"
    image eve 5 = "Eve/1/eve_5.png"
    image eve 6 = "Eve/1/eve_6.png"
    image eve 7 = "Eve/1/eve_7.png"
    image eve 8 = "Eve/1/eve_8.png"
    image eve 9 = "Eve/1/eve_9.png"
    image eve 10 = "Eve/1/eve_10.png"
    image eve 11 = "Eve/1/eve_11.png"
    image eve 12 = "Eve/1/eve_12.png"
    image eve 13 = "Eve/1/eve_13.png"
    image eve 14 = "Eve/1/eve_14.png"
    image eve 15 = "Eve/1/eve_15.png"
    image eve 16 = "Eve/1/eve_16.png"
    image eve 17 = "Eve/1/eve_17.png"
    image eve 18 = "Eve/1/eve_18.png"
    image eve 19 = "Eve/1/eve_19.png"
    image eve d1 = "Eve/1/eve_d1.png"
    image eve d2 = "Eve/1/eve_d2.png"
    image eve d3 = "Eve/1/eve_d3.png"
    image eve d4 = "Eve/1/eve_d4.png"
    image eve d5 = "Eve/1/eve_d5.png"
    image eve d6 = "Eve/1/eve_d6.png"
    image eve d7 = "Eve/1/eve_d7.png"
    image eve d8 = "Eve/1/eve_d8.png"
    image eve 1b = "Eve/2/eve2_1.png"
    image eve 2b = "Eve/2/eve2_2.png"
    image eve 3b = "Eve/2/eve2_3.png"
    image eve 4b = "Eve/2/eve2_4.png"
    image eve 5b = "Eve/2/eve2_5.png"
    image eve 6b = "Eve/2/eve2_6.png"
    image eve 7b = "Eve/2/eve2_7.png"
    image eve 8b = "Eve/2/eve2_8.png"
    image eve 9b = "Eve/2/eve2_9.png"
    image eve 10b = "Eve/2/eve2_10.png"
    image eve 11b = "Eve/2/eve2_11.png"
    image eve 12b = "Eve/2/eve2_12.png"
    image eve 13b = "Eve/2/eve2_13.png"
    image eve 14b = "Eve/2/eve2_14.png"
    image eve 15b = "Eve/2/eve2_15.png"
    image eve 16b = "Eve/2/eve2_16.png"
    image eve 17b = "Eve/2/eve2_17.png"
    image eve 18b = "Eve/2/eve2_18.png"
    image eve 19b = "Eve/2/eve2_19.png"
    image eve 20b = "Eve/2/eve2_20.png"
    image eve 21b = "Eve/2/eve2_21.png"
    image eve 22b = "Eve/2/eve2_22.png"
    image eve 23b = "Eve/2/eve2_23.png"
    image eve 24b = "Eve/2/eve2_24.png"
    image eve d1b = "Eve/2/eve2_d1.png"
    image eve d2b = "Eve/2/eve2_d2.png"
    image eve d3b = "Eve/2/eve2_d3.png"
    image eve d4b = "Eve/2/eve2_d4.png"
    image eve d5b = "Eve/2/eve2_d5.png"
    image eve d6b = "Eve/2/eve2_d6.png"
    image eve d7b = "Eve/2/eve2_d7.png"
    image eve d8b = "Eve/2/eve2_d8.png"
    image eve d9b = "Eve/2/eve2_d9.png"
    image eve d10b = "Eve/2/eve2_d10.png"
    # CHARACTER DEF JAMS
    define e = Character('Eve')
    define mom = Character('Ryo\'s Mom')
    define dad = Character('Ryo\'s Dad')
    define r = Character('Ryo')
    define dad2 = Character('Eve\'s Dad')
    define girlA = Character('Girl A')
    define girlB = Character('Girl B')
    define k1 = Character('Kid 1')
    define k2 = Character('Kid 2')
    define k3 = Character('Kid 3')
    define k4 = Character('Kid 4')
    define k5 = Character('Kids')
    define Chika = Character('Chika')
    define Jiro = Character('Jiro')
    define Shigeru = Character('Shigeru')
    define teacher = Character('Teacher')
label start:
    #WEETABIX NOTE: Insert splash screen particulars here.
    $ love_points = 0
    $ meeting1_flag = false
    $ money_flag = false
	jump begin
label begin:
    scene black
    $renpy.pause(0.5)
    play sound "clock.wav"
    $renpy.pause(1)
    #play music "Music/White Snow.ogg"
    $renpy.pause(3)
    mom "Ryo, you need to get up you are going to be late for school."
    r "Ugh... Just five, five more minutes."
    mom "Honestly what is the point of even setting an alarm if you ignore it all the time."
    mom "It is time to get up, young man. I will not allow you to be late for school."
    r "..........."
    mom "Ryo, you better be up and awake by the time I get back, or there will be consequences."
    r "Alright... alright, I\'m getting up."
    mom "Good, now hurry down for breakfast."
    "With a groan Ryo crawled out of bed. Letting out a yawn he dressed himself in his uniform in a foggy haze. His body was still half asleep causing him to sway back and forth as he headed out of his room and to the kitchen."
    scene bg house_in1
    mom "Good morning, today I made a-"
    mom "You are not going to school looking like that are you?"
    "Ryo glanced up and down at what he was wearing a shrugged."
    r "Why not?"
    "He was wearing clothes, so he wasn\'t in his underwear, and he had his uniform on. He wondered what was wrong with what he was wearing."
    "Ryo\'s mom let out a sigh and shook her head. She reached into her pocket and magically pull out a comb."
    mom "Your hair is a mess. You can\'t go to school looking like that."
    "In a swift motion without waiting for her son\'s reply began to comb his hair. Combing it until it reached her approval, despite Ryo\'s protests."
    r "Mom, stop. I can do it myself. I\'m not a little kid. It is embarrassing."
    "She smiled at her son and stopped fussing over him, allowing him control over his hair once again."
    mom "Oh, just look at you. You\'re still half asleep. You look like you are about to fall asleep again."
    #play sound "sprayer.wav"
    #WEETABIX NOTE: WHERE'S THE SPRAYER GODDAMNIT?
    r "Mom! What are you doing stop!?"
    mom "Sorry, I thought it would wake you up."
    "Ryo glared at his mother as he took the hand towel she held out to him."
    mom "Honestly sometimes you act just like a little child."
    r "I\'m the child? It is pretty childlike in my eyes to spray someone with the sprayer."
    mom "Don\'t take everything so seriously. Have a little fun with life."
    play sound "toaster.wav"
    r "Toast for breakfast today?"
    mom "Ding. Ding. Ding. You\'ve guessed correctly. Today I decided to make a western breakfast. But we had no eggs, so just toast."
    "Ryo shook his head at his mother\'s antics. He wondered just how in the world his mom and dad got together, they were complete opposites. His dad was always serious and hardly ever joked around, while his mother was almost never serious."
    mom "Here you go Ryo. I even cut the crust off so it would be easier for you to eat."
    "Ryo glared at the good being offered to him. It wasn\'t that he didn\'t like toast. No, in fact he actually liked toast. Nor was it the fact that his mother had made it."
    "He hated the extra attention that his mother had put into it. He was not a little kid and he did not want to be treated like one, ever."
    r "Thanks..."
    "He took the piece of toast and took one bite from the center of it before throwing the remainder away."
    "Ryo\'s mother quickly masked her slight disappointment and wished him a safe trip."
    "Ryo had only eating a tiny bit of the toast and had thrown away the majority of it. It was just a simple action, but it held deeper meaning to her. It reminded of of how whenever she tried to get closed to her son, he would throw her feelings away."
    r "Well, I\'m off."
    mom "Have a safe trip."
    "Ryo bundled himself up in a winter coat and hat before heading out the door."
    scene bg house1
    "Currently there was no snow falling, but the cold march weather still caused a chill in the air."
    "A crisp breeze caused the trees to sway back and forth, and made the day feel much harsher than it was. It made the 0 C day feel more like -5 C" 
    "Ryo slung his bag over his shoulder and set out for school. The school was pretty far away over a thirty minute walk away."
    "On normal days Ryo didn\'t mind that his school was such a distance away, but on cold days like this one he hated it."
    scene black
    "School was hectic the students were all in excitement and it was noisy due to White Day being only a few days away."
    "Ryo settled into his chair and tried to ignore the noisy atmosphere. White Day meant nothing to him, so he had no reason to join in the chatter about it."
    "He had received nothing for any girl on Valentines Day, so he had no obligation to give any girl anything on White Day."
    "Ryo disregarded the nasty words spoken about him and his attitude. He was at the very top of the school in terms of grades."
    "When he first started at the school everyone was impressed with his grades and he was looked up to. But after a while when other students found out how little effort he put into getting those grades, he became despised by almost all the school."
    "Ryo was at the university level already, but his parents had thought it would be better to have him go through high school, like a normal teen. They thought it would be a good experience."
    "However so far the only real thing he had come to experience was how shallow and jealous teens can be, and how envy can change a person."
    teacher "Alright settle down. We are going to have a test today. Everyone try do their best."
    "Ryo finished filling in the test and then waiting for everyone else to finish."
    "The school day dragged on as usual until the sweet sound signaling freedom rang out. Ryo gathered together his stuff and threw it all in his bag before beginning the long journey home."
    scene bg bridge1
    #play music "Music/Waters Surface.ogg" 
    "Ryo stopped when he came to the bridge. Cars zoomed by like normal, drowning out all sound when they passed. The busy street had cars going both ways at a frequent pace almost all hours of the day."
    "Something was different. Something was out of place."
    "The normally empty bridge had someone standing there. Draped in a black cloak the person seemed to be starring at the water down below."
    "Something felt off about this person. They seemed to have entranced them-self in their own little world. As if a bubble was around them, completely shutting out everything around them."
    "What was the reason behind their attire. It seemed to offer little to no protection from the wind and the cold. Ryo was curious, the person seemed to different and out of place. He felt that they had a unquiqe and interesting tale."
    "Ryo felt that something about this person was special. He wanted to know just why there were there lost in their own world."
    "They were a mystery, something different to shake up his boring day to day lifestyle, or at least that is what he hoped."
